config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'get/*query', to: 'products#index'  
  get 'terms-and-conditions', to:'home#terms'
  get 'privacy-policy', to:'home#privacy'
  post 'user_login', to: 'home#user_login'
  get 'login', to: 'home#login'
  get 'team', to: 'home#team'
  get 'careers', to: 'home#careers'

  get 'search/', to: 'products#index'
  get 'products/', to: 'products#index'
  get 'products/:category/:sub_category/:brand/:name', to: 'products#show'
  post 'products', to:'products#index'
  post 'suggested_list', to: 'products#suggested_list'
  

  get 'stores', to:'stores#index'
  get 'favourites-list', to: 'stores#favourites_list'
  get 'stores/:store_area/:name', to: 'stores#show'

  post 'stores', to:'stores#index'
  post 'set_favourite', to: 'stores#set_favourite'
  post 'remove_favourite', to: 'stores#remove_favourite'
  post 'favourites-list', to: 'stores#favourites_list'
  get 'profile', to: 'stores#profile'
  post 'profile', to: 'stores#profile'
  get 'my-profile', to: 'stores#my_profile'
  post 'my-profile', to: 'stores#my_profile'
  post 'set_name', to: 'stores#set_name_profile'
  post 'set_mobile', to: 'stores#set_mobile_profile'
  post 'set_profile', to: 'stores#set_profile'
  post 'feedback', to: 'stores#feedback'

  get '/blogs', to: 'blogs#index'
  get '/blogs/:title', to: 'blogs#show'
  get 'blogs/:title/change', to: 'blogs#edit'
  post 'blogs/update', to: 'blogs#update'
  post '/blogs/post_to_blog', to: 'blogs#post_to_blog'
  get '/write/a/blog/', to: 'blogs#new'
  post 'contact_us', to: 'user#contact_us'
  post 'send_resume', to: 'home#send_resume'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index
		blogs = URI("http://mapprr.ws/blogs")
		blogs = Net::HTTP.get(blogs)
		@blogs = JSON.parse(blogs)['blogs'].reverse
	end

	def create
	end

	def show
		blog_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/blogs/#{params['title']}" ), {})
		@blog_data = JSON.parse(blog_data.body)
		if @blog_data['blog'].present?
			@blog = @blog_data['blog']
		else
			@blog = nil
		end
	end

	def post_to_blog
	    cover_image = 'blog.jpg'
	    if blog_params['cover_image'].present?
			obj = S3_BUCKET.objects[blog_params['cover_image'].original_filename]
	    
		    obj.write(
		      file: blog_params['cover_image'],
		      acl: :public_read
		    )
		    cover_image = "https://s3.ap-south-1.amazonaws.com/mapprr/" + blog_params['cover_image'].original_filename
	    end
	    @blog={
	    	"title" => blog_params['title'].upcase,
	    	"content" => blog_params['content'],
	    	"cover_image" => cover_image
	    }
	    blog = Net::HTTP.post_form(URI.parse("http://mapprr.ws/blogs?blog="), @blog)
		redirect_to blogs_path
	end

	def edit
		blog_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/blogs/#{params['title'].parameterize}" ), {})
		blog_data = JSON.parse(blog_data.body)
		if blog_data['blog'].present?
			@blog = blog_data['blog']
		else
			@blog = nil
		end
	end

	def update
		@blog={
	    	"title" => blog_params['title'].upcase,
	    	"content" => blog_params['content'],
	    	"description" => blog_params['description'],
	    	"keywords" => blog_params['keywords']
	    }
	    blog_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/blogs/change?id="+params[:id] ), @blog)
	    redirect_to blogs_path
	end

	def destroy
	end

	private
	def blog_params
		params.require(:blog).permit(:title, :content, :cover_image, :description, :keywords)
	end
end

app/views/blogs/edit.html.erb
<body class="b_bg">
	<nav class="navbar navbar-light productnav" role="navigation">
		<div class="container" style="margin:18px auto;">
			<div class="navbar-left col-sm-6 col-md-3">
				<a href="/"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/footer.svg", :class => "img-responsive nav_logo", :alt => "Mapprr") %></a>
			</div>
		</div>
	</nav>
	<div class="panel panel-default col-md-8 col-md-offset-2">
		<div class="panel-body">
		<h3 class="text-center">Write a Blog</h3>
			<form action="<%= blogs_update_path(id: @blog['id']) %>" method="POST" class="create_blog" enctype="multipart/form-data">
				<div class="form-group">
    				<label for="blog[title]">Title of your Blog</label>
					<input type="text" autofocus="autofocus" name="blog[title]" class="form-blog" placeholder="Blog Title" value="<%= @blog['title'] %>" required="true">
				</div>
				<div class="form-group">
					<label for="blog[content]">Content of your Blog</label>
					<textarea rows="4" type="text" autofocus="autofocus" name="blog[content]" class="form-blog ckeditor" placeholder="Content" required="true"><%= raw @blog['content'] %></textarea>
				</div>
				<div class="form-group">
    				<label for="blog[description]">Description of your Blog</label>
					<input type="text" autofocus="autofocus" name="blog[description]" class="form-blog" value="<%= @blog['description'] %>" placeholder="Blog Description">
				</div>
				<div class="form-group">
    				<label for="blog[keywords]">Keywords of your Blog</label>
					<input type="text" autofocus="autofocus" name="blog[keywords]" class="form-blog" placeholder="Blog keywords" value="<%= @blog['keywords'] %>">
				</div>
                <button class="btn btn-success pull-right blog-btn" type="submit">Post</button>
			</form>
		</div>
	</div>
</body>

app/views/blogs/index.html.erb
<% content_for :head do %>
    <title>Mapprr | Blog</title>
    <meta name="description" content="By reading the articles of Mapprr you get more information and search the products availability in your nearby stores with a single tap.">
    <meta name="keywords" content="blogs, popular blogs, blog sites, blog post, blog websites, best blogs">
<% end %>
<div class="container-fluid" style="background-color: #fafafa;">
        <div class="container text-right">
            <div class="upper-links">
            <span class="p_user_login" id="user_login"></span>
            <ul class="p_user_dropdown dropdown-menu">
              <li id="profile" class="profile-li"><a class="profile-links" id="profile_link" href="/my-profile?query=">Profile Info</a></li>
              <li id="fav" class="profile-li"><a class="profile-links" id="fav_link" href="/favourites-list?query=">Favourites</a></li>
              <li id="logout" class="profile-li"><a class="profile-links" href="">Logout</a></li>
            </ul>
        </div>
        </div>
    </div>
 <nav class="navbar navbar-light productnav" role="navigation">
<div class="container" style="margin:18px auto;padding-left: 0px;padding-right: 0px;">
        <div class="navbar-left col-sm-6 col-md-3 col-xs-5 logo"> <a href="/"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/footer.svg", :class => "img-responsive nav_logo", :alt => "Mapprr") %></a></div>

      <div class="col-sm-6 col-md-3 col-xs-7 col-sx-push-0 col-md-push-6 loc_m text-right" style="margin-top: 15px;">
        <div style="width:100%;">
        <a class="p-location" data-toggle="dropdown"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/location_pin2.png", :alt => "Location icon", :width=> "13px") %> <span id="geolocation">Choose your location</span></a>

          <ul class="dropdown-menu c_loc" role="menu" style="border: 0;border-radius: 0;margin: 0;padding: 15px 7px;position: absolute;top: 100%;right: 0;left:auto;">
              <li class="dropdown-header" style="color: #263238;  ">Select Location</li>
              <li id="profile" class="profile-li" style="padding:7px 12px;">
                <form id="mform" method="post" action="javascript:;" data-toggle="validator" role="form">

                  <div class="input-group" style="border:1px solid #bdbdbd;">
                    <input id="m_loc" type="text" class="f-control" placeholder="Type your location..." style="border:0px; min-width: 250px" />
                    <span class="input-group-btn" style="border-left: 1px solid #bdbdbd;padding:1px;">
                    <button class="btn btn-secondary" id="detect_loc" type="button" style="background-color: #fff;"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/location_pin2.png", :alt => "Location icon", :width=> "13px") %></button>
                    </span>
                  </div>
                </form>
              </li>
          </ul>
        </div>
      </div>
  <!--     <div class="three"> -->
        <div class="col-sm-12 col-md-6 col-xs-12 col-sx-pull-0 col-md-pull-3 search_f " style="margin-top: 7px;">
            <form action="<%= products_path() %>" method="POST" id="p_form" itemprop="potentialAction" itemscope itemtype="http://schema.org/SearchAction">
          <meta itemprop="target" content="https://mapprr.com/products?product={search_query}"/>
            <div class="input-group searchbox-input2">
                <input type="text" id="search_query" name="search_query" itemprop="query-input" class="form-control searchtxt2" placeholder="What are you looking for?" autocomplete="off" required="true">
                <div class="input-group-btn">
                  <button class="btn btn-default searchbtn2" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
            </div>
        </form>
            </div>
   <!--  </div> -->
   <!--  <div class="two"> -->
        
<!--     </div> -->

</div>
    </nav>
	<div class="container" style="margin-bottom: 30px;">
    <div class="row">
      <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
          <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a itemprop="item" href="/"><span itemprop="name">Home</span></a><meta itemprop="position" content="1" /></li>
          <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a itemprop="item" href="/blogs"><span itemprop="name">Blogs</span></a><meta itemprop="position" content="2" /></li>
        </ol>
    </div>
        <div class="row">
                <div class="col-md-12"><h2 class="text-center">Blogs</h2></div>
        </div>
	   <% @blogs.each do |blog| %>
			<div class="col-md-6 blog-grid">
                <div class="blog blog-inverse blog-info">
                    <%= image_tag blog['cover_image'], :class => 'img-responsive blog-img' %>
                    <div class="blog-block">
                        <h3 class="blog-title"><a href="/blogs/<%= blog['title'].parameterize %>"><%= blog['title'] %></a></h3>
                        <div class="blog-text content-flow">
                            <%= raw blog['content'] %>
                        </div>
                    </div>
                    <div class="blog-footer">
                        <span class="time"><%= time_ago_in_words(blog['created_at']) %> ago</span>
                        <span><a href="/blogs/<%= blog['title'].parameterize %>" class="float-right ">Read More...</a></span>
                    </div>
                </div>
            </div>
	   <% end %>
	</div>

     <div id="snackbar"></div>



<script async src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">
    <script async src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript">
      var blocation = window.localStorage.getItem("slocation");
      if (blocation == null)
    {
    
        detectLocation();
    }
    else
    {
        $("#geolocation").html(blocation);

    }
   

    //location icon click then auto dectect location
    $("#detect_loc").click(function(){
                detectLocation();
            $("#m_loc").val(blocation);
          });

    </script> 
<script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZUpobR20JfD78lRFdkVU2VV1joDsBVjA&libraries=places&callback=initAutocomplete">
    </script>

app/views/blogs/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blogs</title>
</head>
<body class="b_bg">
	<nav class="navbar navbar-light productnav" role="navigation">
		<div class="container" style="margin:18px auto;">
			<div class="navbar-left col-sm-6 col-md-3">
				<a href="/"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/footer.svg", :class => "img-responsive nav_logo", :alt => "Mapprr") %></a>
			</div>
		</div>
	</nav>
	<div class="panel panel-default col-md-8 col-md-offset-2">
		<div class="panel-body">
		<h3 class="text-center">Write a Blog</h3>
			<form action="<%= blogs_post_to_blog_path %>" method="POST" class="create_blog" enctype="multipart/form-data">
				<div class="form-group">
    				<label for="blog[title]">Title of your Blog</label>
					<input type="text" autofocus="autofocus" name="blog[title]" class="form-blog" placeholder="Blog Title" required="true">
				</div>
				<div class="form-group">
					<label for="blog[cover_image]">Cover Image for your Blog</label>
					<input type="file" name="blog[cover_image]" class="form-blog">
				</div>
				<div class="form-group">
					<label for="blog[content]">Content of your Blog</label>
					<textarea rows="4" type="text" autofocus="autofocus" name="blog[content]" class="form-blog ckeditor" placeholder="Content" required="true"></textarea>
				</div>
				<div class="form-group">
    				<label for="blog[description]">Description of your Blog</label>
					<input type="text" autofocus="autofocus" name="blog[description]" class="form-blog" placeholder="Blog Description">
				</div>
				<div class="form-group">
    				<label for="blog[keywords]">Keywords of your Blog</label>
					<input type="text" autofocus="autofocus" name="blog[keywords]" class="form-blog" placeholder="Blog keywords">
				</div>
                <button class="btn btn-success pull-right blog-btn" type="submit">Post</button>
			</form>
		</div>
	</div>
</body>
</html>

app/views/blogs/show.html.erb
<% content_for :head do %>
    <title>Mapprr | <%= @blog_data['blog']['title'].capitalize %></title>
    <meta name="description" content="<%= @blog_data['blog']['description'] %>">
    <meta name="keywords" content="<%= @blog_data['blog']['keywords'] %>">
    <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5aa27666d362000013e3b11f&product=social-ab' async='async'></script>
    <!-- Metadata Facebook -->
    <meta content='Mapprr' property='og:site_name'/>
    <meta content="<%= 'Mapprr: ' + @blog_data['blog']['title'] %>" property='og:title'/>
    <meta content="<%= 'https://mapprr.com/blogs/' + @blog_data['blog']['title'].parameterize %>" property='og:url'/>
    <meta property="og:image" content="<%= @blog_data['blog']['cover_image'] %>" />
    <meta content='170855293693841' property='fb:app_id'/>
    <!-- Metadata Twitter -->
    <meta name='twitter:card' content='summary'/>
    <meta name="twitter:url" content="https://mapprr.com">
    <meta content="<%= 'Mapprr: ' + @blog_data['blog']['title'] %>" name='twitter:title'/>
    <meta content="<%= @blog_data['blog']['cover_image'] %>" name="twitter:image:src" />
    <meta content="<%= raw @blog_data['blog']['content'][0..200] %>" name="twitter:description" />
    <meta content='@mapprr' name='twitter:site'/>
    <meta content='@mapprr' name='twitter:creator'/>
<% end %>
<div class="container-fluid" style="background-color: #fafafa;">
        <div class="container text-right">
            <div class="upper-links">
            <span class="p_user_login" id="user_login"></span>
            <ul class="p_user_dropdown dropdown-menu">
              <li id="profile" class="profile-li"><a class="profile-links" id="profile_link" href="/my-profile?query=">Profile Info</a></li>
              <li id="fav" class="profile-li"><a class="profile-links" id="fav_link" href="/favourites-list?query=">Favourites</a></li>
              <li id="logout" class="profile-li"><a class="profile-links" href="">Logout</a></li>
            </ul>
        </div>
        </div>
    </div>
 <nav class="navbar navbar-light productnav" role="navigation">
<div class="container" style="margin:18px auto;padding-left: 0px;padding-right: 0px;">
        <div class="navbar-left col-sm-6 col-md-3 col-xs-5 logo"> <a href="/"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/mapprr-logo3.png", :class => "img-responsive", :alt => "Location icon") %> </a></div>

      <div class="col-sm-6 col-md-3 col-xs-7 col-sx-push-0 col-md-push-6 loc_m text-right" style="margin-top: 15px;">
        <div style="width:100%;">
        <a class="p-location" data-toggle="dropdown"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/location_pin2.png", :alt => "Location icon", :width=> "13px") %> <span id="geolocation">Choose your location</span> <i style="display:none;" class="fa fa-spinner fa-pulse fa-fw loading"></i></a>

          <ul class="dropdown-menu c_loc" role="menu" style="border: 0;border-radius: 0;margin: 0;padding: 15px 7px;position: absolute;top: 100%;right: 0;left:auto;">
              <li class="dropdown-header" style="color: #263238;  ">Select Location</li>
              <li id="profile" class="profile-li" style="padding:7px 12px;">
                <form id="mform" method="post" action="javascript:;" data-toggle="validator" role="form">

                  <div class="input-group" style="border:1px solid #bdbdbd;">
                    <input id="m_loc" type="text" class="f-control" placeholder="Type your location..." style="border:0px; min-width: 250px" />
                    <span class="input-group-btn" style="border-left: 1px solid #bdbdbd;padding:1px;">
                    <button class="btn btn-secondary" id="detect_loc" type="button" style="background-color: #fff;"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/location_pin2.png", :alt => "Location icon", :width=> "13px") %></button>
                    </span>
                  </div>
                </form>
              </li>
          </ul>
        </div>
      </div>
  <!--     <div class="three"> -->
        <div class="col-sm-12 col-md-6 col-xs-12 col-sx-pull-0 col-md-pull-3 search_f " style="margin-top: 7px;">
            <form action="<%= products_path() %>" method="POST" id="p_form" itemprop="potentialAction" itemscope itemtype="http://schema.org/SearchAction">
          <meta itemprop="target" content="https://mapprr.com/products?product={search_query}"/>
            <div class="input-group searchbox-input2">
                <input type="text" id="search_query" name="search_query" itemprop="query-input" class="form-control searchtxt2" placeholder="What are you looking for?" autocomplete="off" required="true">
                <div class="input-group-btn">
                  <button class="btn btn-default searchbtn2" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
            </div>
        </form>
            </div>
   <!--  </div> -->
   <!--  <div class="two"> -->
        
<!--     </div> -->

</div>
    </nav>
	<div class="container">
    <div class="row">
      <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
          <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a itemprop="item" href="/"><span itemprop="name">Home</span></a><meta itemprop="position" content="1" /></li>
          <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a itemprop="item" href="/blogs"><span itemprop="name">Blogs</span></a><meta itemprop="position" content="2" /></li>
          <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a itemprop="item" href="/blogs/<%= params[:title] %>"><span itemprop="name"><%= @blog['title'].capitalize %></span></a><meta itemprop="position" content="3`" /></li>
        </ol>
    </div>
</div>	
		<div class="row" style="margin-bottom: 30px;">
		<div class="col-sm-10 col-md-offset-1">
			<h2 class="blog-title text-center" id="blog-title"><%= @blog['title'] %></h2>
			<div class="text-center">
				<%= image_tag @blog['cover_image'], :class => 'img-responsive blog_img' %>
			</div>
			<h5 class="time"><%= Time.parse(@blog['created_at']).strftime("%A") %>, <%= Time.parse(@blog['created_at']).day %> <%= Date::MONTHNAMES[Time.parse(@blog['created_at']).month] %>, <%= Time.parse(@blog['created_at']).year %></h5>
			<br/>
			<div class="show-content"><%= raw @blog['content'] %></div>
		</div>
    <div class="sharethis-inline-share-buttons" style="padding-top: 20px;"></div>
	</div>
	</div>

 <div id="snackbar"></div>


<script async src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">
    <script async src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript">
      var blocation = window.sessionStorage.getItem("slocation");
      if (blocation == null)
    {
    
        detectLocation();
    }
    else
    {
        $("#geolocation").html(blocation);

    }
   

    //location icon click then auto dectect location
    $("#detect_loc").click(function(){
                detectLocation();
            $("#m_loc").val(blocation);
          });

    </script> 
<script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZUpobR20JfD78lRFdkVU2VV1joDsBVjA&libraries=places&callback=initAutocomplete">
    </script>