config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'get/*query', to: 'products#index'  
  get 'terms-and-conditions', to:'home#terms'
  get 'privacy-policy', to:'home#privacy'
  post 'user_login', to: 'home#user_login'
  get 'login', to: 'home#login'
  get 'team', to: 'home#team'
  get 'careers', to: 'home#careers'

  get 'search/', to: 'products#index'
  get 'products/', to: 'products#index'
  get 'products/:category/:sub_category/:brand/:name', to: 'products#show'
  post 'products', to:'products#index'
  post 'suggested_list', to: 'products#suggested_list'
  

  get 'stores', to:'stores#index'
  get 'favourites-list', to: 'stores#favourites_list'
  get 'stores/:store_area/:name', to: 'stores#show'

  post 'stores', to:'stores#index'
  post 'set_favourite', to: 'stores#set_favourite'
  post 'remove_favourite', to: 'stores#remove_favourite'
  post 'favourites-list', to: 'stores#favourites_list'
  get 'profile', to: 'stores#profile'
  post 'profile', to: 'stores#profile'
  get 'my-profile', to: 'stores#my_profile'
  post 'my-profile', to: 'stores#my_profile'
  post 'set_name', to: 'stores#set_name_profile'
  post 'set_mobile', to: 'stores#set_mobile_profile'
  post 'set_profile', to: 'stores#set_profile'
  post 'feedback', to: 'stores#feedback'

  get '/blogs', to: 'blogs#index'
  get '/blogs/:title', to: 'blogs#show'
  get 'blogs/:title/change', to: 'blogs#edit'
  post 'blogs/update', to: 'blogs#update'
  post '/blogs/post_to_blog', to: 'blogs#post_to_blog'
  get '/write/a/blog/', to: 'blogs#new'
  post 'contact_us', to: 'user#contact_us'
  post 'send_resume', to: 'home#send_resume'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	#before_action :authenticate_user
  	def index
  		if params[:query].present?
		  	key_params = encode_key()
			@stores_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/stores/get_store_details?key="+key_params), {})
			# binding.pry
			@stores_data = JSON.parse(@stores_data.body)
			stores = @stores_data['stores']
			if stores.present?
				distance_params = params["query"].split(",")[2,2].join(',')
				store_distances = ""
				stores.each do |store|
					store_distances += store["location"]["lat"].to_s + "," + store["location"]["lng"].to_s + "|"
				end
				distance_data = Net::HTTP.post_form(URI.parse("https://maps.googleapis.com/maps/api/distancematrix/json?origins="+distance_params+"&destinations="+store_distances+"&key=AIzaSyAZUpobR20JfD78lRFdkVU2VV1joDsBVjA"), {})
				distance_data = JSON.parse(distance_data.body)
				@distances = []
				distance_data["rows"].first["elements"].each do |dd|
					@distance = []
					@distance << dd["distance"]["text"]
					@distance << dd["duration"]["text"]
					@distances << @distance
				end
				for i in 0..stores.length-1
					stores[i].merge!("distance" => @distances[i], "address" => distance_data["destination_addresses"][i])
				end
			end
			stores = stores.sort_by{|store| store['distance']}
			@stores =[]
			stores.each do |store|
				@stores << store if store['is_bookmarked']
			end
			stores.each do |store|
				@stores << store unless store['is_bookmarked']
			end
			@similar_products = @stores_data['similar_products']
			# binding.pry
		else
			@stores = "404"
		end
		# puts stores
	end

	def my_profile
		key_params = encode_key()
		redirect_to profile_path(query: key_params)
	end

	def profile
		key_params = params["query"]
		response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/consumers/get_profile_info?key="+key_params), {})
		response_data = JSON.parse(response_data.body)
		#binding.pry
		@name = response_data["name"]
		@dob = response_data["dob"]
		@mobile = response_data["mobile"]
		@gender = response_data["gender"]
		@recent_products = response_data["recent_products"]
		#binding.pry
	end

	def set_profile
		key_params = encode_key()
		response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/consumers/set_profile?key="+key_params), {})
		# binding.pry
		render status: response_data.code.to_i, json:{"message" => JSON.parse(response_data.body)['message'], "activation_status" => JSON.parse(response_data.body)['activation_status']}
	end

	def set_name_profile
		key_params = encode_key()
		response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/consumers/set_name?key="+key_params), {})
		render status: response_data.code.to_i, json:{"message" => JSON.parse(response_data.body)['message']}
	end

	def set_mobile_profile
		key_params = encode_key()
		response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/consumers/set_mobile?key="+key_params), {})
		render status: response_data.code.to_i, json:{"message" => JSON.parse(response_data.body)['message']}
	end

	def set_favourite
		key_params = encode_key()
		response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/stores/set_favourite?key="+key_params), {})
		render status: response_data.code.to_i, json:{"message" => JSON.parse(response_data.body)['message']}
	end

	def remove_favourite
		key_params = encode_key()
		response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/stores/remove_favourite?key="+key_params), {})
		render status: response_data.code.to_i, json:{"message" => JSON.parse(response_data.body)['message']}
	end

	def favourites_list
		if params[:query].present?
			key_params = encode_key()
			response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/stores/favourites_list?key="+key_params), {})
			response_data = JSON.parse(response_data.body)
			favourite_stores = response_data['favourite_stores']
			if favourite_stores.present?
				distance_params = params["latlng"]
				store_distances = ""
				favourite_stores.each do |store|
					store_distances += store["location"]["lat"].to_s + "," + store["location"]["lng"].to_s + "|"
				end
				distance_data = Net::HTTP.post_form(URI.parse("https://maps.googleapis.com/maps/api/distancematrix/json?origins="+distance_params+"&destinations="+store_distances+"&key=AIzaSyAZUpobR20JfD78lRFdkVU2VV1joDsBVjA"), {})
				distance_data = JSON.parse(distance_data.body)
				@distances = []
				distance_data["rows"].first["elements"].each do |dd|
					@distance = []
					@distance << dd["distance"]["text"]
					@distance << dd["duration"]["text"]
					@distances << @distance
				end
				for i in 0..favourite_stores.length-1
					favourite_stores[i].merge!("distance" => @distances[i], "address" => distance_data["destination_addresses"][i])
				end
			end
			@favourite_stores = favourite_stores.sort_by{|store| store['distance']}
		else
			@favourite_stores = "404"
		end
	end

	def feedback
		key_params = encode_key()
		response_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/consumers/feedback?key="+key_params), {})
		response_data = JSON.parse(response_data.body)
	end

	def show
	    store_data = Net::HTTP.post_form(URI.parse("http://mapprr.ws/stores/get_store?store_area="+params[:store_area]+"&name="+params[:name]), {})
	    @store_data = JSON.parse(store_data.body)
	    if @store_data["store"].present?
	    	# binding.pry
	      @store = @store_data["store"]
	    else
	      @store = nil
	    end
	end

	private

	  	def encode_key
	  		query = params["query"]
	  		iv = '1234567890123456'
	  		api_key_hash = {"mapprr"=>"12345678908905672341765890432165"}
	  		key = api_key_hash["mapprr"]
	  		acipher = OpenSSL::Cipher::Cipher.new("aes-256-cbc")
		      acipher.encrypt
		      acipher.key = key
		      acipher.iv = iv
	     	encrypted_string = acipher.update(query) + acipher.final
	     	val = Base64.encode64(encrypted_string).strip
	     	val
	  	end

	  	def store_params
  			params.permit(:query)
  		end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/favourites_list.html.erb
<% content_for :head do %>
    <title>Mapprr | My favourite stores list</title>
    <meta name="description" content="If you’re visiting the same store often which is near your location then adding to your favourites list makes the product easy to access.">
    <meta name="keywords" content="mapprr, mapper, pharmacy near me, medical near me, medical store near me, shops near me, medicine app, 24 hr pharmacy near me">
<% end %>
<body class="s_bg">
		<div class="container-fluid" style="background-color: #fdfdfd;">
		<div class="container text-right">
			<div class="dropdown">
			<a class="p_user_login dropdown-toggle" id="user_login" data-toggle="dropdown">Hi <span id="user_name"></span> <span class='caret'></span></a>
            <ul class="p_user_dropdown dropdown-menu">
              <li id="profile"><a id="profile_link" href="/my-profile?query=">Profile Info</a></li>
              <li id="logout"><a href="#">Logout</a></li>
            </ul>
        </div>
		</div>
	</div>
<nav class="navbar navbar-light productnav" role="navigation">
<div class="container" style="margin:18px auto;">
  <div class="col-xs-6 col-sm-6 col-md-6">
	  	<div class="navbar-left"> <a href="/"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/footer.svg", :class => "img-responsive nav_logo", :alt => "Mapprr") %>  </a></div>
    </div>

    <div class="col-xs-6 col-sm-6 col-md-6">
	    <div class="text-right" style="margin-top: 20px;">
	    	<a href="/" class="empty_state">Back to search</a>
	    </div>
    </div>
</div>
	</nav>

<div class="container" style="min-height: 50vh;">
	<!-- store list grid -->
		<% if not @favourite_stores.present? %>
			<div class="col-md-12 text-center" style="height:100vh;">
				<%= image_tag( "https://s3.ap-south-1.amazonaws.com/mapprr/empty_bookmarks.png", :class => "card-img-top", :height => "52%", :alt => "Store image") %>
				<h4 class="empty_state">Your favourite list is empty.</h4>
			</div>
		<% elsif @favourite_stores == "404" %>
			<div class="col-md-12 text-center" style="height:100vh;">
				<%= image_tag( "https://s3.ap-south-1.amazonaws.com/mapprr/empty_bookmarks.png", :class => "card-img-top", :height => "52%", :alt => "Store image") %>
				<h4 class="empty_state">Favourtes depend on each individual. Please login and check your list.</h4>
			</div>
		<% else %>
		<div class="col-md-12 store-grid">
		<% @favourite_stores.each do |s| %>
	
	<!-- products row 1-->
		
			<div class="col-xs-12 col-sm-6 col-md-6" style="padding:5px;">
				<div class="store-card row">
				<div class="col-md-4 col-sm-12 col-xs-12 storeimg">
						
					<% if s['image_url'].present? %>
						  <%= image_tag( "#{s['image_url']}", :class => "card-img-top img-responsive", :alt => "Store image") %>
						<% else %>
						  <%= image_tag(('https://s3.ap-south-1.amazonaws.com/mapprr/default2.png'), :class => "card-img-top img-responsive", :alt => "Store image" ) %>
						<% end %>
				</div>
				<div class="col-md-8 col-sm-12 col-xs-12">
					  <div class="card-block">
					    <div class="row">
					    	<h4 class="store-title"><span class="titleonly"><%= s['name'] %></span> <span class="pull-right" style="color:#66BB6A;font-size:12px;line-height:16px;"> <%= s['distance'][0] %></span></h4>

					    </div>
					    <div class="row">
					    <p class="store-address"><%= s['address'] %></p>
						</div>
						<div class="actions row">
					    <div style="margin:10px auto;"><span style="margin:auto 15px auto 0px; width:28px;"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/clock.png", :alt => "Location icon", :width=> "18px") %></span><span class="store-title-sub"> 7AM - 11PM</span></div>

					    <div class="store-location" style="margin-top:15px;">
					    	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center" style="border-right: 1px solid #ccc;"><a class="btn" style="padding:7px 9px;width: 100%;" data-toggle="modal" data-target="#phone_<%= s['id'] %>">
  							<%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/call2.svg", :alt => "Location icon", :height=> "21px;") %></a>
  							</div>
	  						<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center" style="border-right: 1px solid #ccc;"><a class="btn" target="_blank" style="padding:7px 9px;">
	  							
	  							<i id ="<%= s['id'] %>" class="fa fa-heart fa-lg bookmark" aria-hidden="true" style="font-size: 21px;"></i>
	  						</a>

	  						</div>
	  						<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center store-location" style=""><a class="btn map_direction" style="padding:7px 9px; width: 100%;" href='<%= "http://maps.google.com/maps?daddr=#{ s['location']['lat']}, #{s['location']['lng']}" %>' id="item_<%= s['id'] %>" target="_blank">
	  							<%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/map_marker.svg", :alt => "Location icon", :height=> "21px;") %></a>
	  						</div>

					    </div>


						<!-- Modal -->
						  <div class="modal fade" id="phone_<%= s['id'] %>" role="dialog">
						    <div class="modal-dialog model-sm" style="max-width: 400px;margin: 60px auto;">
						      <div class="modal-content">
						        <div class="modal-header" style="padding: 15px;">
						          <button type="button" class="close" data-dismiss="modal">&times;</button>
						          <h4 class="modal-title"><%= s['name'] %></h4>
						          <p class="store-address" style="max-width: 300px; color:#ffffff;"><%= s['address'] %></p>
						        </div>
						        <div class="modal-body" style="padding: 25px;">
						          <p style="font-size: 16px;letter-spacing: 1px;text-align: center;">Call to <%= s['phone'] %></p>
						        </div>
						      </div>
						    </div>
						  </div>
					    
					    </div>


 
					  </div>	
				</div>
		</div>	
	</div>
	<!--end list-->
	
	
	<% end %>
	</div>
	<% end %>
	<!-- filter end -->
</div>

 <div id="snackbar"></div>

<script>
$(document).ready(function(){
	var latlong = window.localStorage.getItem("latlng");
	var user = window.localStorage.getItem("user");
	var name = window.localStorage.getItem("name");
  $("#user_name").html(name);

if (user !=null)
{
	$(document).ready();
}
else
{
	 window.location.href="/";
}



	//map directions
$(".map_direction").click(function(){
	$(this).attr('href', $(this).attr('href') +'&saddr='+latlong);
});

	$("#logout").click(function(){
	  window.localStorage.clear();
	  window.location.href="/";
	});
//bookmark

	$('i.fa-heart').click(function(){
	    $(this).toggleClass('fa-heart fa-heart-o')
	    var setbookmark = user + "," + this.id;
	    var reqData ={};
	    reqData.query = setbookmark;
	    $.ajax({
	    	type:'POST',
	    	url: '<%= remove_favourite_path() %>',
	    	data:reqData,
	    	success:function()
	    	{
	    		window.location.reload(true);
	    		var x = $("#snackbar")
			      x.addClass("show")
			        .html("Removed from your favourite list");
			      setTimeout(function() {
			         x.removeClass("show");
			     }, 3000);
	    		
	    	}
	    });
	});




	var plocation = window.localStorage.getItem("slocation");
	    $("#geolocation").html(plocation);
	//profile


});


</script>
<script async defer
		    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcP9FK8X5VZyQuzOaoNpVcY_zwCQJ7C_A">
		    </script>
<script async src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">
<script async src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
</body>

app/views/stores/show.html.erb
<% content_for :head do %>
    <title>Mapprr | Select a nearest store to call or locate on map</title>
    <meta name="description" content="Mapprr provides you the list of nearest stores for any product with its contact details. You can locate the store on our inbuilt map interface. Now locating a store is easy and hassle-free.">
    <meta name="keywords" content="mapprr, mapper, pharmacy near me, medical near me, medical store near me, shops near me, medicine app, 24 hr pharmacy near me">
<% end %>
<div class="s_bg">
	<div class="container-fluid" style="background-color: #fdfdfd;">
		<div class="container text-right">
			<div class="dropdown">
				<a class="p_user_login dropdown-toggle" id="user_login" data-toggle="dropdown"></a>
            	<ul class="p_user_dropdown dropdown-menu">
            		<li id="profile" class="profile-li"><a class="profile-links" id="profile_link" href="/my-profile?query=">Profile Info</a></li>
              		<li id="fav" class="profile-li"><a class="profile-links" id="fav_link" href="/favourites-list?query=">Favourites</a></li>
              		<li id="logout" class="profile-li"><a class="profile-links" href="#">Logout</a></li>
            	</ul>
        	</div>
		</div>
	</div>
	<nav class="navbar navbar-light productnav" role="navigation">
		<div class="container" style="margin:18px auto;">
	  		<div class="navbar-left col-sm-6 col-md-3 col-xs-5"><a href="/"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/footer.svg", :class => "img-responsive nav_logo", :alt => "Mapprr") %></a></div>
	  		<div class="col-sm-6 col-md-3 col-xs-7 col-sx-push-0 col-md-push-6 loc_m text-right" style="margin-top: 10px;">
	    		<a class="p-location"><%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/location_pin2.png", :alt => "Location icon", :width=> "14px") %> <span id="geolocation"></span></a>
	    	</div>
	  		<div class="col-sm-12 col-md-6 col-xs-12 col-sx-pull-0 col-md-pull-3 search_f">
	  			<form action="<%= products_path() %>" method="POST" id="p_form">
	  				<div class="input-group searchbox-input2">
			    		<input type="text" id="search_query" name="search_query" class="form-control searchtxt2" placeholder="What are you looking for?" autocomplete="off" required="true">
			    		<div class="input-group-btn">
					      <button class="btn btn-default searchbtn2" type="submit">
					        <i class="glyphicon glyphicon-search"></i>
					      </button>
					    </div>
					</div>
				</form>
			</div>
	    </div>
	</nav>

	<div class="container" style="margin:30px auto;">
		<% if @store.nil? %>
			<h1><%= @store_data["message"] %></h1>
		<% else %>
		 <div class="col-md-3" style="">
		<% if @store['image_url'].present? %>
			<%= image_tag( "#{@store['image_url']}", :class => "card-img-top img-responsive img-rounded", :alt => "Store image") %>
		<% else %>
			<%= image_tag(('https://s3.ap-south-1.amazonaws.com/mapprr/default2.png'), :class => "card-img-top img-responsive img-rounded", :alt => "Store image" ) %>
		<% end %>
		</div>
		<div class="col-md-5" style="margin-top: 20px;">
			<h1 style=""><%= @store['name'] %></h1>
			<h2 style="font-size:20px;"><%= @store['address_line1'] %>, <%= @store['address_area'] %>, <%= @store['city'] %>.</h2>
			<div class="" style="margin-top: 20px;">
				<%= image_tag("https://s3.ap-south-1.amazonaws.com/mapprr/call2.svg", :alt => "Location icon", :height=> "18px;") %>
				<span style="margin-left: 7px;font-size:18px;line-height: 10px;vertical-align: middle;color:rgb(93,194,120);font-weight: lighter;letter-spacing: 1px;"><%= @store['phone'] %></span>
				</div>

		</div>
			<div class="col-md-4">
		      
		    </div>
		<% end %>
	</div>
</div>